### PR TITLE
feat: merge dict chapter with common collections

### LINKED ISSUE #308: refactor: Arrays and Dictionaries in a Common Collections chapter

### PR DESCRIPTION
**Pull request by julio4**
Close #308

The Common Collections chapter is now quite large. It might be a good idea to split it into a larger chapter called Collections, which could come after the Common Programming Concepts chapter [Common Programming Concepts](https://book.cairo-lang.org/ch02-00-common-programming-concepts.html). Let me know what you think.

### CODE REVIEW

**Comment by enitrat** [comment]
Agreed - please create a new chapter and add Arrays and Dictionaries as sub-chapters

**Comment by julio4** [comment]
Done!

**Review by enitrat — APPROVED** [review]
Looks good!

**Comment by enitrat** [comment]
Actually no, oops, we need to move the listings to the correct folders please @julio4 !

**Comment by julio4** [comment]
> Actually no, oops, we need to move the listings to the correct folders please @julio4 !

Oh sorry, my bad I missed that! I'll do it right now!

**Comment by enitrat** [comment]
yes, it's fine

**Review by enitrat — APPROVED** [review]
Thanks Jules 🔥

**Pull request merged**
