### PR TITLE
Add Simplified Chinese(zh-cn)  translation for the Cairo book.

### PR DESCRIPTION
**Pull request by cryptonerdcn**
Hey guys! We added a Simplified Chinese(zh-cn)  translation for the Cairo book.
Only added a zh-cn.po file, base on main after merged https://github.com/cairo-book/cairo-book.github.io/pull/161.
You can see it online here: https://starknetastro.github.io/cairo-book.github.io/zh-cn/title-page.html (*NB*: This online version is just for zh-cn demo so I changed more codes than this `zh-cn` branch.)

And I have a question: Should I modify the `index.hbs` file and `LANGUAGES` file in order to show the zh-cn item in the `language-list` just like es and fr?

### CODE REVIEW

**Comment by cryptonerdcn** [comment]
@fricoben @enitrat @glihm Can you review this PR? Thanks a lot!

**Comment by fricoben** [comment]
What a gigantic work, thx. 

My 2 years of Chinese in school won't help for the review here but we'll take a look if it works nicely with i18 (language plugin)

**Comment by cryptonerdcn** [comment]
> What a gigantic work, thx.
> 
> My 2 years of Chinese in school won't help for the review here but we'll take a look if it works nicely with i18 (language plugin)
> 

Thanks! I believe after installing, `./translations.sh zh-cn` will work.
> Can you describe a bit what was your methodology to translate all of that ? Thx !

This is not finished all by myself alone. We(StarknetAstro) worked together, and they have chosen me to create this pull request. 
By using [poedit](https://poedit.net/), each of us can translate a small portion of the text (although this "small portion" is still significant). 
Fortunately, we have a good relationship with the Chinese rust community. They have translated the Rust-book into [Chinese](https://github.com/rust-lang-cn/book-cn) and suggested we should take a look at it.  Because Cairo-book shares similar content with Rust-book, we can follow the example of the Chinese version to guide our translation. 
For sth. rust doesn't have (such as snapshot), some developers in Astro who are familiar with Cairo(such as me) will handle it.

**Comment by enitrat** [comment]
amazing, thanks. Is this ready to be merged?

**Comment by cryptonerdcn** [comment]
> amazing, thanks. Is this ready to be merged?

If there is no need to modify the `index.hbs` file and `LANGUAGES` file to show the Chinese version in the `language-list`, I think it is ready for merge.

**Comment by enitrat** [comment]
> index.hbs file and LANGUAGES

please modify then and add the `zh-cn` option!

**Comment by cryptonerdcn** [comment]
> > index.hbs file and LANGUAGES
> 
> please modify then and add the `zh-cn` option!

It's done. You can see the demo [here](https://starknetastro.github.io/cairo-book.github.io/index.html).

**Review by enitrat — APPROVED** [review]
Thank you!

**Comment by glihm** [comment]
Amazing work guys. 🚀

**Pull request merged**
