### PR TITLE
refactor: use type inferance, remove type literals

### PR DESCRIPTION
**Pull request by enitrat**

### CODE REVIEW

**Comment by cryptonerdcn** [comment]
There are still some type-literals in the codes.
Such as https://github.com/cairo-book/cairo-book.github.io/blob/c467ef274ef2fd617f8d00d470a7a3d0affe1e7e/src/ch02-02-data-types.md?plain=1#L100

Are you still working on it or will these be changed in another branch?

**Review by cryptonerdcn — APPROVED** [review]
I am not a reviewer for this repo yet but I want to say: LGTM
BB8 Thumbs Up

**Review by cryptonerdcn — APPROVED** [review]
LGTM

**Comment by enitrat** [comment]
I will treat it as an official approval ;) Thanks!

**Pull request merged**
