### PR TITLE
Updated Chapter 12.3.1

### PR DESCRIPTION
**Pull request by OkoliEvans**
There was no description on how to write  user defined struct to storage, and how to read as well. Added these with examples. @enitrat

### CODE REVIEW

**Comment by OkoliEvans** [comment]
> I don't understand why reading/writing structs would be separated from other types. How to read and write variables from storage is already explained here
> 
> https://book.cairo-lang.org/ch99-01-03-01-storage-variables.html#reading-from-storage

I will edit and commit again in a few hours

**Comment by OkoliEvans** [comment]
Updated now, Please check @enitrat

**Comment by enitrat** [comment]
Sorry, what I meant was:

Storing user defined structs is equivalent to storing any other kind of data. Read and writes are performed in the same way as well which is why I do not understand why there would be a section specifically about structs. 

The example provided do not compile and don't make a lot of sense (why is a Person stored under a variable named `name`?) 

For eventual subsequent PRs, you will need to verify that the examples compile first, and then add them to the `listings` directory, as it's currently done for all code snippets

**Comment by OkoliEvans** [comment]
I thought adding the changes will make it clearer to understand how structs annotated with ```#[derive(starknet::Store)]``` are written to. In the book there is no explicit explanation about how this is done, the usual ```self.names.write(value)``` does not work for user defined storage structs.

**Comment by enitrat** [comment]
> the usual self.names.write(value) does not work for user defined storage structs. @enitrat

It does! There is no difference between compiler-defined types, enums, or structs! You just call `self.var.write(value)` !

**Comment by OkoliEvans** [comment]
Oh, I tried that yesterday and I was getting errors. I will confirm and pm you on Telegram. Thank you

**Pull request closed without merging**
