### PR TITLE
fixing emit event snippet

### PR DESCRIPTION
**Pull request by gaetbout**

### CODE REVIEW

**Comment by gaetbout** [comment]
@enitrat idk who handles the PR here, so pinging you

**Comment by enitrat** [comment]
@gaetbout you would also need to modify the markdown file please!

**Comment by gaetbout** [comment]
@enitrat wdym, I have to make a new ref file?
Because the `ch99-01-03-03-contract-events.md` file points to this one

**Comment by enitrat** [comment]
Yes but inside the markdown file we use the Event:: syntax

**Comment by gaetbout** [comment]
Indeed, hope it is correct now

**Review by enitrat — APPROVED** [review]
LGTM ty!

**Pull request merged**
