### PR TITLE
Update ch99-01-04-01-voting-contract.md

### PR DESCRIPTION
**Pull request by OkoliEvans**
@enitrat Is this good now?

### CODE REVIEW

**Comment by enitrat** [comment]
@OkoliEvans I will check but please avoid opening a new PR at each change, you can just apply the changes to your branch and push for them to be applied

**Review by enitrat — APPROVED** [review]
LGTM 🔥

**Comment by OkoliEvans** [comment]
> LGTM 🔥

Thank you very much : )

**Comment by OkoliEvans** [comment]
> @OkoliEvans I will check but please avoid opening a new PR at each change, you can just apply the changes to your branch and push for them to be applied

Alright Ser, I couldn't find a way to edit the book locally, but I will try to find it next time.

**Pull request merged**
