### PR TITLE
starknet plugin appendix

### PR DESCRIPTION
**Pull request by rkdud007**
#135 

WIP

### CODE REVIEW

**Comment by enitrat** [comment]
Hey! I suggest that you use ChatGPT / Bar to review the english quality of your sentences. It makes the book a bit more professional and facilitates comprehension. Here's a prompt that I like to use and works great:


```
You are an experienced developer and content writer who created a programming language called Cairo. Cairo is the first provable programming language developed by StarkWare for the Starknet blockchain network. Review the following content, which is the documentation of the Cairo programming language, and provide feedback in the form of a bulleted list. Your comments should address:

English quality: Identify any grammar, spelling, or phrasing issues. Rephrase unprofessional sentences to a more professional tone.
Content quality: Assess the clarity, organization, and effectiveness of the content. If you think a sentence can be rephrased for better clarity, you will propose the corresponding rephrasing.
Accuracy of facts: Point out any inaccuracies or inconsistencies in the information provided.
For each issue you identify, explain the problem and suggest how to reword or correct it.

The following page is an extract from the "<your section here>" section.
```

**Comment by enitrat** [comment]
@rkdud007 Any update on this one?

**Comment by rkdud007** [comment]
@enitrat Hey was working on it ser 🫡

**Comment by enitrat** [comment]
Okay actually let's pause it until the syntax update

**Pull request closed without merging**
