### PR TITLE
feat: Transitioning Cairo Content to Cairo Book and Introducing Intermediate to Advanced Smart Contract Examples

### PR DESCRIPTION
**Pull request by omarespejel**
This PR initiates the migration of Cairo-related content from the Starknet Book to the Cairo Book. Specifically, Chapter 12 of the Cairo Book has been updated with selected content from the Starknet Book. This change aims to consolidate all Cairo-related material within the Cairo Book.

I propose the addition of a new section titled "Other Examples." This section will serve as a platform for the community to contribute intermediate to advanced examples of smart contracts. As a part of this initiative, I have included a Voting contract that has proven valuable in teaching Cairo for Starknet to budding developers. This curated section is intended to assist developers in learning through practical examples.

We also show how to deploy the contract and interact with it using a local node with Katana.

### CODE REVIEW

**Review by enitrat — COMMENTED** [review]
Thanks @omarespejel this is great! 
I think we should find a better title for that section, as just "Voting Contract" is not very indicative. The title should indicate that we're also going to deploy and interact with this contract

**Comment by omarespejel** [comment]
✅ Thank you @enitrat. I changed the title to "Deploying and Interacting with a Voting contract"; it is indeed a better name.

image

**Review by enitrat — APPROVED** [review]
LGTM! 💯

**Comment by omarespejel** [comment]
Thank you, @enitrat. We will redirect people interested in learning Cairo for Starknet to the Cairo Book 🚀

**Pull request merged**
